name: Build Latest Dictionary Files

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Environment
      run: pip3 install opencc
    
    - name: Build
      run: make zhwiki.dict zhwiki.dict.yaml


