name: Build Latest Dictionary Files

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Prepare Environment
      run: |
          pip3 install opencc pypinyin
          sudo apt install libime-bin
    
    - name: Build
      run: make zhwiki.dict zhwiki.dict.yaml


